### Numpy-> Numerical Python
### Pandas-> dataset
### Matplotlib -> Data Visualization
### Seaborn -> Data Visualization
### Scipy -> Statistical
### Sklearn -> ML Algorithms

In [2]:
import numpy as np

In [ ]:
arr=np.array([1,2,3])
arr

In [ ]:
list_of_lists=[1,2,3],[4,5,6],[7,8,8]
np.array(list_of_lists)

In [ ]:
np.arange(5,20)

In [ ]:
np.arange(20)

In [ ]:
np.arange(1,21,2)

In [ ]:
np.zeros(10)

In [ ]:
np.zeros(10,int)

In [ ]:
np.ones(10)

In [ ]:
np.ones(10,int)

In [ ]:
np.ones((2,5))

In [ ]:
np.ones((2,5),int)

In [ ]:
np.linspace(0,2,5)

In [ ]:
np.linspace(0,1,4)

In [ ]:
np.random.rand(3,5)

In [ ]:
np.random.randn(3,5)

In [ ]:
np.random.randint(3,50)

In [ ]:
np.random.randint(3,10,100)

In [3]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
sample_array.reshape(5,6)

In [ ]:
sample_array.reshape(3,10)

In [ ]:
sample_array.reshape(3,6)

In [ ]:
sample_array.max()

In [ ]:
sample_array.min()

In [4]:
sample_array+sample_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [5]:
np.exp(sample_array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12])

In [6]:
np.log(sample_array)

C:\Users\Premalatha\AppData\Local\Temp\ipykernel_21276\988743405.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(sample_array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [7]:
np.sqrt(sample_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [8]:
np.exp(sample_array)

29

In [9]:
np.min(sample_array)

0

In [10]:
np.square(sample_array)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [11]:
np.std(sample_array)

8.65544144839919

In [12]:
np.mean(sample_array)

14.5

In [13]:
np.median(sample_array)

14.5

In [14]:
np.var(sample_array)

74.91666666666667

In [15]:
array=np.random.rand(4,5)
array

array([[0.07027783, 0.79506342, 0.54306554, 0.77920262, 0.25299195],
       [0.86605568, 0.42368406, 0.96131778, 0.82319616, 0.75508403],
       [0.68425924, 0.77335255, 0.11761319, 0.1895422 , 0.39585633],
       [0.21276884, 0.57605439, 0.18085285, 0.94145685, 0.10152518]])

In [17]:
np.round(array,3)

array([[0.07 , 0.795, 0.543, 0.779, 0.253],
       [0.866, 0.424, 0.961, 0.823, 0.755],
       [0.684, 0.773, 0.118, 0.19 , 0.396],
       [0.213, 0.576, 0.181, 0.941, 0.102]])

In [19]:
sports=np.array(['golf','cricket','football','cricket'])

In [20]:
sports

array(['golf', 'cricket', 'football', 'cricket'], dtype='<U8')

In [21]:
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')

In [30]:
sample_matrix=np.array([[50,21,23,12],[24,56,28,76],[24,13,12,1]])
sample_matrix

array([[50, 21, 23, 12],
       [24, 56, 28, 76],
       [24, 13, 12,  1]])

In [31]:
sample_matrix[1,2]

28

In [32]:
sample_matrix[2,:]

array([24, 13, 12,  1])

In [33]:
sample_matrix[:,(3,2)]

array([[12, 23],
       [76, 28],
       [ 1, 12]])

In [34]:
sample_matrix[2,(1,2)]

array([13, 12])

### Pandas

In [35]:
import pandas as pd

In [36]:
df=pd.read_csv("AutoInsurance.csv")

In [37]:
df.head()

Customer       State  Customer Lifetime Value Response  Coverage Education  \
0  BU79786  Washington              2763.519279       No     Basic  Bachelor   
1  QZ44356     Arizona              6979.535903       No  Extended  Bachelor   
2  AI49188      Nevada             12887.431650       No   Premium  Bachelor   
3  WW63253  California              7645.861827       No     Basic  Bachelor   
4  HB64268  Washington              2813.692575       No     Basic  Bachelor   

  Effective To Date EmploymentStatus Gender  Income  ...  \
0           2/24/11         Employed      F   56274  ...   
1           1/31/11       Unemployed      F       0  ...   
2           2/19/11         Employed      F   48767  ...   
3           1/20/11       Unemployed      M       0  ...   
4          3/2/2011         Employed      M   43836  ...   

  Months Since Policy Inception Number of Open Complaints  Number of Policies  \
0                             5                         0                   1   
1                            42                         0                   8   
2                            38                         0                   2   
3                            65                         0                   7   
4                            44                         0                   1   

      Policy Type        Policy  Renew Offer Type  Sales Channel  \
0  Corporate Auto  Corporate L3            Offer1          Agent   
1   Personal Auto   Personal L3            Offer3          Agent   
2   Personal Auto   Personal L3            Offer1          Agent   
3  Corporate Auto  Corporate L2            Offer1    Call Center   
4   Personal Auto   Personal L1            Offer1          Agent   

  Total Claim Amount  Vehicle Class Vehicle Size  
0         384.811147   Two-Door Car      Medsize  
1        1131.464935  Four-Door Car      Medsize  
2         566.472247   Two-Door Car      Medsize  
3         529.881344            SUV      Medsize  
4         138.130879  Four-Door Car      Medsize  

[5 rows x 24 columns]